# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 311)
        self.MyForm = QtWidgets.QLabel(Form)
        self.MyForm.setGeometry(QtCore.QRect(120, 50, 121, 20))
        self.MyForm.setLineWidth(1)
        self.MyForm.setObjectName("MyForm")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Моя первая форма"))
        self.MyForm.setText(_translate("Form", "   Здесь будет текст"))
        self.pushButton.setText(_translate("Form", "Приветствие"))
